/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun day01exists() {
        assertNotNull(Day01, "day01 should exist")
    }
}
