/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun day01HasAPart1() {
        val classUnderTest = Day01()
        assertNotNull(Day01.part1, "day01 should have a part1")
    }
}
