/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

fun main() {

    val path = System.getProperty("user.dir")

    println("Working Directory = $path")

    val input = readInput("Day03")
    println(Day03.part1(input))
    println(Day03.part2(input))
}
