/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

fun main() {
    val input = readInput("Day12")
    println(Day12.part1(input))
    println(Day12.part2(input))
}
