/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

fun main() {
    val input = readInput("Day22")
    println(Day22.part1(input))
    println(Day22.part2(input))
}
